#!/bin/bash

# conf file is where everything else is defined.
source conf

# Almost nothing happens here, all the functions are defined elsewhere.
for file in $(ls functions/*.sh)
do
    echo "Adding function: $(head -n 1 $file | cut -d " " -f 1)"
    source $file
done

# Setting current location and recreating the work folder.
CWD=$(pwd)
if [ ! -d $WORK_DIR ]
then
    mkdir -p $WORK_DIR
fi
cd $WORK_DIR
echo "Work dir: $(pwd)"

START=$(date +%s)

# This is where functions are executed.
run ()
{
    echo "[$(date +%T)] Running $1 $2" | tee -a $LOG_FILE
    SECONDS=0
    $1
    echo "$1 finished with no errors and ran for $(time_diff $SECONDS)" | tee -a $LOG_FILE
}

clean_env ()
{
    run clean
    run clean_vms
    run clean_pool
    run clean_vnets
    run restart_libvirt
}

clean_env 

echo "ALL DONE in $(time_diff $(( $(date +%s) - $START)))"
