heat_template_version: 2016-04-08

description: >
  These resources are nedded by heat_integrationtests.

parameters:
  public_network_name:
    type: string
    default: public

  private_network_name:
    type: string
    default: heat-net

  public_subnet_name:
    type: string
    default: public_subnet
  public_subnet_cidr:
    type: string
    default: 172.16.0.0/24
  public_subnet_gateway:
    type: string
    default: 172.16.0.1
  public_pool_start:
    type: string
    default: 172.16.0.10
  public_pool_end:
    type: string
    default: 172.16.0.200

  private_subnet_name:
    type: string
    default: private_subnet
  private_subnet_cidr:
    type: string
    default: 10.0.0.0/24
  private_subnet_gateway:
    type: string
    default: 10.0.0.1
  private_pool_start:
    type: string
    default: 10.0.0.10
  private_pool_end:
    type: string
    default: 10.0.0.200

  glance_image_name:
    type: string
    default: fedora_heat
  glance_image_location:
    type: string
    default: http://dl.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/Fedora-Cloud-Base-25-1.3.x86_64.qcow2

  keypair_name:
    type: string
    default: keypair_heat
  keypair_pubkey:
    type: string
    default: /home/stack/.ssh/id_rsa.pub

resources:

  ### flavors should be removed as soon as they are no longer hard-coded
  flavor:
    type: OS::Nova::Flavor
    properties:
      disk: 1
      ram: 512
      vcpus: 1
      name: m1.tiny

    type: OS::Nova::Flavor
    properties:
      disk: 8
      ram: 2048
      vcpus: 1
      name: m1.small

  public_network:
    type: OS::Neutron::Net
    properties:
      name: {get_param:public_network_name}
      shared: true
      value_specs: {
        "router:external":"true",
        "provider:network_type":"vlan",}

  public_subnet:
    properties:
      name: public_subnet
      network: {get_resource: public_network}
      ip_version: 4
      cidr: {get_param: public_subnet_cidr}
      gateway_ip: {get_param: public_subnet_gateway}
      allocation_pools:
        - start: {get_param: public_pool_start}
          end: {get_param: public_pool_end}

  private_network:
    type: OS::Neutron::Net
    properties:
      name: heat-net

  private_subnet:
    properties:
      name: private_subnet
      network: {get_resource: private_network}
      ip_version: 4
      cidr: {get_param: private_subnet_cidr}
      gateway_ip: {get_param: private_subnet_gateway}
      allocation_pools:
        - start: {get_param: private_pool_start}
          end: {get_param: private_pool_end}

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_resource: public_network}

  router_gateway:
    type: OS::Neutron::RouterGateway
    properties:
      router_id: {get_resource: router}
      network_id: {get_resource: public_network}

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: private_subnet}

  glance_image:
    type: OS::Glance::Image
    properties:
      container_format: bare
      disk_format: qcow2
      is_public: true
      location: {get_param: glance_image_name}
      min_disk: 8
      min_ram: 1024
      name: {get_param: glance_image_name}
      protected: false

  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: {get_param: keypair_name}
      public_key: {get_param: keypair_pubkey}

outputs:
  public_network_id:
    description: Public network ID
    value: {get_resource: public_network}
  public_subnet_id:
    description: Public subnet ID
    value: {get_resource: public_subnet}
  private_network_id:
    description: Private network ID
    value: {get_resource: private_network}
  private_subnet_id:
    description: Private subnet ID
    value: {get_resource: private_subnet}
